package info.jafe.emboard.entity;
// Generated 2015-10-2 19:04:46 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable {

	private int postid;
	private String topic;
	private Date datetime;
	private String body;
	private String tag;
	private int id;
	private byte flowers;

	public Post() {
	}

	public Post(int postid, String topic, Date datetime, String tag, int id, byte flowers) {
		this.postid = postid;
		this.topic = topic;
		this.datetime = datetime;
		this.tag = tag;
		this.id = id;
		this.flowers = flowers;
	}

	public Post(int postid, String topic, Date datetime, String body, String tag, int id, byte flowers) {
		this.postid = postid;
		this.topic = topic;
		this.datetime = datetime;
		this.body = body;
		this.tag = tag;
		this.id = id;
		this.flowers = flowers;
	}

	public int getPostid() {
		return this.postid;
	}

	public void setPostid(int postid) {
		this.postid = postid;
	}

	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public byte getFlowers() {
		return this.flowers;
	}

	public void setFlowers(byte flowers) {
		this.flowers = flowers;
	}

}
