package info.jafe.emboard.entity;
// Generated 2015-10-2 19:04:46 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Repost generated by hbm2java
 */
public class Repost implements java.io.Serializable {

	private int repostid;
	private User user;
	private int postid;
	private Date datetime;

	public Repost() {
	}

	public Repost(int repostid, User user, int postid, Date datetime) {
		this.repostid = repostid;
		this.user = user;
		this.postid = postid;
		this.datetime = datetime;
	}

	public int getRepostid() {
		return this.repostid;
	}

	public void setRepostid(int repostid) {
		this.repostid = repostid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getPostid() {
		return this.postid;
	}

	public void setPostid(int postid) {
		this.postid = postid;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
