package info.jafe.emboard.entity;
// Generated 2015-10-4 17:46:12 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Repost generated by hbm2java
 */
public class Repost implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1176988860307420409L;
	private int repostid;
	private int id;
	private int postid;
	private Date datetime;

	public Repost() {
	}

	public Repost(int repostid, int id, int postid, Date datetime) {
		this.repostid = repostid;
		this.id = id;
		this.postid = postid;
		this.datetime = datetime;
	}

	public int getRepostid() {
		return this.repostid;
	}

	public void setRepostid(int repostid) {
		this.repostid = repostid;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getPostid() {
		return this.postid;
	}

	public void setPostid(int postid) {
		this.postid = postid;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
