package info.jafe.emboard.entity;
// Generated 2015-10-4 11:49:14 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Repost generated by hbm2java
 */
@Entity
@Table(name = "_repost", catalog = "emboard")
public class Repost implements java.io.Serializable {

	private int repostid;
	private int id;
	private int postid;
	private Date datetime;

	public Repost() {
	}

	public Repost(int repostid, int id, int postid, Date datetime) {
		this.repostid = repostid;
		this.id = id;
		this.postid = postid;
		this.datetime = datetime;
	}

	@Id

	@Column(name = "repostid", unique = true, nullable = false)
	public int getRepostid() {
		return this.repostid;
	}

	public void setRepostid(int repostid) {
		this.repostid = repostid;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "postid", nullable = false)
	public int getPostid() {
		return this.postid;
	}

	public void setPostid(int postid) {
		this.postid = postid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", nullable = false, length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
