package info.jafe.emboard.entity;
// Generated 2015-10-4 11:49:14 by Hibernate Tools 3.5.0.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="_user"
    ,catalog="emboard"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class User  implements java.io.Serializable {


     private int id;
     private String email;
     private String nickname;
     private String password;
     private String gender;
     private Byte authority;
     private byte postcount;
     private int points;
     private byte flowers;
     private String signature;
     private Date regdate;
     private byte[] icon;
     private boolean online;

    public User() {
    }

	
    public User(int id, String email, String password, String gender, byte postcount, int points, byte flowers, Date regdate, boolean online) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.gender = gender;
        this.postcount = postcount;
        this.points = points;
        this.flowers = flowers;
        this.regdate = regdate;
        this.online = online;
    }
    public User(int id, String email, String nickname, String password, String gender, Byte authority, byte postcount, int points, byte flowers, String signature, Date regdate, byte[] icon, boolean online) {
       this.id = id;
       this.email = email;
       this.nickname = nickname;
       this.password = password;
       this.gender = gender;
       this.authority = authority;
       this.postcount = postcount;
       this.points = points;
       this.flowers = flowers;
       this.signature = signature;
       this.regdate = regdate;
       this.icon = icon;
       this.online = online;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="email", unique=true, nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="nickname", length=20)
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    
    @Column(name="password", nullable=false, length=41)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="gender", nullable=false, length=2)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="authority")
    public Byte getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(Byte authority) {
        this.authority = authority;
    }

    
    @Column(name="postcount", nullable=false)
    public byte getPostcount() {
        return this.postcount;
    }
    
    public void setPostcount(byte postcount) {
        this.postcount = postcount;
    }

    
    @Column(name="points", nullable=false)
    public int getPoints() {
        return this.points;
    }
    
    public void setPoints(int points) {
        this.points = points;
    }

    
    @Column(name="flowers", nullable=false)
    public byte getFlowers() {
        return this.flowers;
    }
    
    public void setFlowers(byte flowers) {
        this.flowers = flowers;
    }

    
    @Column(name="signature")
    public String getSignature() {
        return this.signature;
    }
    
    public void setSignature(String signature) {
        this.signature = signature;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="regdate", nullable=false, length=19)
    public Date getRegdate() {
        return this.regdate;
    }
    
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    
    @Column(name="icon")
    public byte[] getIcon() {
        return this.icon;
    }
    
    public void setIcon(byte[] icon) {
        this.icon = icon;
    }

    
    @Column(name="online", nullable=false)
    public boolean isOnline() {
        return this.online;
    }
    
    public void setOnline(boolean online) {
        this.online = online;
    }




}


